---
- name: Verify if i2c interface is active
  command: "raspi-config nonint get_i2c"
  register: i2c_status

- name: Activate I2C interface
  command: "raspi-config nonint do_i2c 0"
  register: activation_status
  when: i2c_status.stdout == "1"

- name: Verify if in config.txt is baud rate setted on 10000
  lineinfile:
    path: /boot/config.txt
    line: dtparam=i2c_baudrate=10000
    state: present
  
- name: Reboot machine
  reboot:
  when: activation_status.changed == true





